version: 0.0
os: linux

files:
  - source: /
    destination: /codedeploy
    overwrite: true


hooks:
  ApplicationStop:
    - location: scripts/stop_application.sh
      timeout: 300
      runas: root

  BeforeInstall:
    - location: scripts/remove_existing_files.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/copy_new_files.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/start_application.sh
      timeout: 300
      runas: root

  ValidateService:
    - location: scripts/validate_deployment.sh
      timeout: 300
      runas: root
      on-failure: rollback
      rollback:
        - location: scripts/rollback.sh
          timeout: 300
          runas: root
