version: 0.0
os: linux

files:
  - source: /
    destination: /codedeploy
    overwrite: true


hooks:
  ApplicationStop:
    - location: scripts/shutdown.sh
      timeout: 300
      runas: root

  BeforeInstall:
    - location: scripts/remove_existing_files.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/update_app.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/custom_start.sh
      timeout: 300
      runas: root


