
name: Maven Package RHEL

on:
  workflow_dispatch:

  release:
    types: [created]

jobs:
  build-maven-package:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::339712877925:role/CodeDeployRole
          role-session-name: Github-deployment
          aws-region: us-east-1

      - name: Deploy to AWS CodeDeploy
        run: |
          aws deploy create-deployment --application-name TomcatDeployToEc2 --deployment-group-name GithubREHEL --github-location repository=${{ github.repository }},commitId=${{ github.sha }} --parameter-overrides deploymentId=123456789
