# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  workflow_dispatch:
  push:
    branches:
      - develop
  release:
    types: [created]

jobs:
  build-maven-package:
    
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
    - name: Java Version
      run: |
        java --version
    - name: Set environment variables
      run: |
        echo "REPO_OWNER=$(echo "${{ github.repository }}" | cut -d'/' -f1)" >> $GITHUB_ENV
        echo "REPO_NAME=$(echo "${{ github.repository }}" | cut -d'/' -f2)" >> $GITHUB_ENV
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::339712877925:role/CodeDeployRole
        role-session-name: Github-deployment
        region: us-east-1
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Extract project version
      id: extract_version
      run: |
        echo "::set-output name=version::$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)"

    - name: Create tar archive
      run: |
        version=${{ steps.extract_version.outputs.version }}
        tar -czvf Appname-${version}.tar.gz target/*.war pom.xml
    - name: Upload File to S3
      run: |
          aws s3 cp Appname-${version}.tar.gz s3://testwar-viky/Artifacts/
    
