name: Update appsettings.json

on:
  workflow_dispatch:

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Python
      run: sudo apt-get install -y python3

    - name: Replace value using Python
      run: |
        import json

        # Load appsettings.Sit.json
        with open('appsettings.Sit.json', 'r') as sit_file:
            sit_data = json.load(sit_file)
        
        # Load appsettings.json
        with open('appsettings.json', 'r') as app_file:
            app_data = json.load(app_file)

        # Replace the value
        app_data['ConnectionStrings']['Eap.Reporting.ConnectionString']['connectionString'] = \
            sit_data['ConnectionStrings']['Eap.Reporting.ConnectionString']['connectionString']

        # Write the updated content back to appsettings.json
        with open('appsettings.json', 'w') as app_file:
            json.dump(app_data, app_file, indent=2)

      shell: python3

    - name: Upload modified appsettings.json
      uses: actions/upload-artifact@v4
      with:
        name: updated-appsettings
        path: appsettings.json
