name: Update appsettings.json

on:
  workflow_dispatch:

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Extract connection string from SIT file using sed
      run: |
        SIT_VALUE=$(sed -n 's/.*"Eap\.Reporting\.ConnectionString":.*"connectionString": "\(.*\)".*/\1/p' appsettings.Sit.json)
        echo "SIT_VALUE=$SIT_VALUE" >> $GITHUB_ENV

    - name: Replace Eap.Reporting.ConnectionString in appsettings.json using sed
      run: |
        sed -i "s|\(\"Eap.Reporting.ConnectionString\"[^{]*\"connectionString\":\) \"[^\"]*\"|\1 \"$SIT_VALUE\"|g" appsettings.json

    - name: Upload modified appsettings.json
      uses: actions/upload-artifact@v4
      with:
        name: updated-appsettings
        path: appsettings.json
