name: Update appsettings.json

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment file'
        required: true
        default: 'Sit'
        type: choice
        options:
          - Sit
          - Prod
          - Dev

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Use the desired Python version

      - name: Run Python script to replace connection string
        run: python .github/workflows/scripts/replacestring.py appsettings.json appsettings.${{ github.event.inputs.environment }}.json ${{ github.event.inputs.environment }}

      - name: Upload modified appsettings.json
        uses: actions/upload-artifact@v4
        with:
          name: updated-appsettings
          path: appsettings.json
